version: '3'

volumes:
  datafiles:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    volumes:
      - datafiles:/var/opt/mssql/data
    ports:
      - "1433:1433"
    restart: always
    
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SqlExpress!

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=1433
      - DBPASSWORD=SqlExpress!
      - ASPNETCORE_ENVIRONMENT=Development
